import { useTranslations } from "next-intl";
import styles from "./showcase.module.css";

export function WorkIllustration({variant}: {variant: "procurement" | "logistics"}) {
 const t = useTranslations("Work.visual");
 const work = useTranslations("Work");
 if (variant === "procurement") return (
<div className={styles.productVisual} role="img" aria-label={t("procurementAlt")}>
        <div className={styles.dashboard} aria-hidden="true"><div className={styles.appToolbar}><strong>◈ &nbsp; supply / workspace</strong><small><i className={styles.appDot}></i>{t("plant")}</small></div><div className={styles.appGrid}><div className={styles.appSidebar}><i></i><i></i><i></i><i></i></div><div className={styles.appContent}><div className={styles.appTitle}>{t("summary")} <small>{t("week")}</small></div><div className={styles.stats}><div className={styles.stat}><small>{t("requests")}</small><b>24</b><em>{t("sites")}</em></div><div className={styles.stat}><small>{t("approved")}</small><b>18</b><em>{t("roles")}</em></div><div className={styles.stat}><small>{t("pending")}</small><b>06</b><em>{t("assigned")}</em></div></div><table className={styles.dataTable}><thead><tr><th>{t("request")}</th><th>{t("area")}</th><th>{t("status")}</th></tr></thead><tbody><tr><td>{t("materials")}</td><td>{t("operations")}</td><td><span className={styles.badge}>{t("approvedOne")}</span></td></tr><tr><td>{t("safety")}</td><td>{t("plant")}</td><td><span className={styles.badge}>{t("approvedOne")}</span></td></tr><tr><td>{t("parts")}</td><td>{t("maintenance")}</td><td><span className={styles.badge + " " + styles.pending}>{t("inReview")}</span></td></tr></tbody></table></div></div><div className={styles.floatingNote}><span>✓</span><div><strong>{t("synced")}</strong><small>{t("noReentry")}</small></div></div></div>
        <span className={styles.visualCaption}>{work("illustration")}</span>
      </div>
 );
 return (
<div className={styles.productVisual} role="img" aria-label={t("logisticsAlt")}>
        <div className={styles.dashboard} aria-hidden="true"><div className={styles.appToolbar}><strong>◈ &nbsp; fleet / dispatch</strong><small><i className={styles.appDot}></i>{t("live")}</small></div><div className={styles.map}><svg viewBox="0 0 450 260" fill="none" preserveAspectRatio="xMidYMid slice"><path d="M-20 30L470 170M-20 90L470 230M-20 150L320 260M40 -20L-10 280M110 -20L60 280M180 -20L130 280M250 -20L200 280M320 -20L270 280M390 -20L340 280M460 -20L410 280" stroke="#273c3d" strokeWidth="8"/><path d="M-20 30L470 170M-20 90L470 230M-20 150L320 260M40 -20L-10 280M110 -20L60 280M180 -20L130 280M250 -20L200 280M320 -20L270 280M390 -20L340 280M460 -20L410 280" stroke="#172b2e" strokeWidth="5"/><path d="M88 62L222 101L213 148L345 187" stroke="#86d8bd" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/><path d="M59 195L139 217L163 92L319 137" stroke="#92b4ef" strokeWidth="2" strokeDasharray="5 5"/><circle cx="88" cy="62" r="7" fill="#86d8bd" stroke="#12251d" strokeWidth="3"/><circle cx="213" cy="148" r="7" fill="#86d8bd" stroke="#12251d" strokeWidth="3"/><circle cx="345" cy="187" r="7" fill="#86d8bd" stroke="#12251d" strokeWidth="3"/><circle cx="163" cy="92" r="7" fill="#92b4ef" stroke="#12251d" strokeWidth="3"/><rect x="219" y="114" width="55" height="20" rx="4" fill="#244237" stroke="#6d9b88"/><text x="230" y="127" fill="#c0dfd1" fontSize="8" fontFamily="monospace">VH-012</text></svg><span className={styles.mapLabel}>{t("fleet")}</span><div className={styles.mapKey}><span><i></i>{t("enRoute")}</span><span><i style={{background:"#92b4ef"}}></i>{t("reassigned")}</span></div></div></div>
        <div className={styles.phone} aria-hidden="true"><div className={styles.phoneScreen}><div className={styles.phoneNotch}></div><p className={styles.phoneKicker}>{t("myRoute")}</p><p className={styles.phoneTitle}>{t("phoneTitle")}</p><div className={styles.phoneRoute}><div className={styles.phoneStop}>{t("depot")}<small>{t("departed")}</small></div><div className={styles.phoneStop}>{t("north")}<small>{t("nextStop")}</small></div><div className={styles.phoneStop}>{t("east")}<small>{t("updated")}</small></div></div><div className={styles.phoneDone}>✓ {t("confirm")}</div></div></div>
        <span className={styles.visualCaption}>{work("illustration")}</span>
      </div>
 );
}
